CLASSES=\
	jsaf.io.BufferedReader	\
	jsaf.io.fs.AbstractFilesystem	\
	jsaf.io.fs.DefaultMetadata	\
	jsaf.io.fs.IAccessor	\
	jsaf.io.LittleEndian	\
	jsaf.io.PerishableReader	\
	jsaf.io.StreamLogger	\
	jsaf.io.StreamTool	\
	jsaf.provider.AbstractBaseSession	\
	jsaf.provider.AbstractSession	\
	jsaf.provider.SessionFactoryImpl	\
	jsaf.provider.unix.io.driver.AbstractDriver	\
	jsaf.provider.unix.io.driver.AIXDriver	\
	jsaf.provider.unix.io.driver.LinuxDriver	\
	jsaf.provider.unix.io.driver.MacOSXDriver	\
	jsaf.provider.unix.io.driver.SolarisDriver	\
	jsaf.provider.unix.io.UnixFileInfo	\
	jsaf.provider.unix.io.UnixFileSearcher	\
	jsaf.provider.unix.io.UnixFileSerializer	\
	jsaf.provider.unix.io.UnixFilesystem	\
	jsaf.provider.unix.system.BaseUnixSession	\
	jsaf.provider.unix.system.Environment	\
	jsaf.provider.unix.system.UnixSession	\
	jsaf.provider.windows.identity.ACE	\
	jsaf.provider.windows.identity.ActiveDirectory	\
	jsaf.provider.windows.identity.Directory	\
	jsaf.provider.windows.identity.Group	\
	jsaf.provider.windows.identity.LocalDirectory	\
	jsaf.provider.windows.identity.Principal	\
	jsaf.provider.windows.identity.User	\
	jsaf.provider.windows.io.WindowsFileInfo	\
	jsaf.provider.windows.io.WindowsFileSearcher	\
	jsaf.provider.windows.io.WindowsFileSerializer	\
	jsaf.provider.windows.io.WindowsFilesystem	\
	jsaf.provider.windows.powershell.PowershellException	\
	jsaf.provider.windows.powershell.Runspace	\
	jsaf.provider.windows.powershell.RunspacePool	\
	jsaf.provider.windows.registry.BinaryValue	\
	jsaf.provider.windows.registry.DwordValue	\
	jsaf.provider.windows.registry.ExpandStringValue	\
	jsaf.provider.windows.registry.Key	\
	jsaf.provider.windows.registry.LicenseData	\
	jsaf.provider.windows.registry.MultiStringValue	\
	jsaf.provider.windows.registry.NoneValue	\
	jsaf.provider.windows.registry.QwordValue	\
	jsaf.provider.windows.registry.Registry	\
	jsaf.provider.windows.registry.RegistryException	\
	jsaf.provider.windows.registry.RegistrySearcher	\
	jsaf.provider.windows.registry.StringValue	\
	jsaf.provider.windows.registry.Value	\
	jsaf.provider.windows.system.Environment	\
	jsaf.provider.windows.system.WindowsSession	\
	jsaf.provider.windows.wmi.scripting.SWbemObject	\
	jsaf.provider.windows.wmi.scripting.SWbemObjectSet	\
	jsaf.provider.windows.wmi.scripting.SWbemProperty	\
	jsaf.provider.windows.wmi.scripting.SWbemPropertySet	\
	jsaf.provider.windows.wmi.WmiException	\
	jsaf.provider.windows.wmi.WmiProvider	\
	jsaf.test.AD	\
	jsaf.test.Default	\
	jsaf.test.Exec	\
	jsaf.test.FS	\
	jsaf.test.Powershell	\
	jsaf.test.Reg	\
	jsaf.test.WMI	\
	jsaf.util.AbstractEnvironment	\
	jsaf.util.Environment	\
