# Copyright (C) 2011 jOVAL.org.  All rights reserved.
# This software is licensed under the LGPL 3.0 license available at http://www.gnu.org/licenses/lgpl.txt

TOP=..

include $(TOP)/common.mk

all: _provider

_facade:
	@$(MAKE) --keep-going --directory=facade all

clean:
	@$(MAKE) --keep-going --directory=facade clean
