# Copyright (C) 2011 jOVAL.org.  All rights reserved.
# This software is licensed under the LGPL 3.0 license available at http://www.gnu.org/licenses/lgpl.txt

all: _facade

_facade:
	@$(MAKE) --directory=facade all

clean:
	@$(MAKE) --directory=facade clean
