CLASSES=\
	jsaf.JSAFSystem	\
	jsaf.Message	\
	jsaf.intf.io.IFile	\
	jsaf.intf.io.IFileEx	\
	jsaf.intf.io.IFileMetadata	\
	jsaf.intf.io.IFilesystem	\
	jsaf.intf.io.IRandomAccess	\
	jsaf.intf.io.IReader	\
	jsaf.intf.io.IReaderGobbler	\
	jsaf.intf.system.IBaseSession	\
	jsaf.intf.system.IEnvironment	\
	jsaf.intf.system.IProcess	\
	jsaf.intf.system.ISession	\
	jsaf.intf.unix.io.IUnixFileInfo	\
	jsaf.intf.unix.io.IUnixFilesystem	\
	jsaf.intf.unix.io.IUnixFilesystemDriver	\
	jsaf.intf.unix.system.IUnixSession	\
	jsaf.intf.util.IConfigurable	\
	jsaf.intf.util.ILoggable	\
	jsaf.intf.util.IPerishable	\
	jsaf.intf.util.IProperty	\
	jsaf.intf.util.ISearchable	\
	jsaf.intf.windows.identity.IACE	\
	jsaf.intf.windows.identity.IDirectory	\
	jsaf.intf.windows.identity.IGroup	\
	jsaf.intf.windows.identity.IPrincipal	\
	jsaf.intf.windows.identity.IUser	\
	jsaf.intf.windows.io.IWindowsFileInfo	\
	jsaf.intf.windows.io.IWindowsFilesystem	\
	jsaf.intf.windows.powershell.IRunspace	\
	jsaf.intf.windows.powershell.IRunspacePool	\
	jsaf.intf.windows.registry.IBinaryValue	\
	jsaf.intf.windows.registry.IDwordValue	\
	jsaf.intf.windows.registry.IExpandStringValue	\
	jsaf.intf.windows.registry.IKey	\
	jsaf.intf.windows.registry.ILicenseData	\
	jsaf.intf.windows.registry.IMultiStringValue	\
	jsaf.intf.windows.registry.INoneValue	\
	jsaf.intf.windows.registry.IQwordValue	\
	jsaf.intf.windows.registry.IRegistry	\
	jsaf.intf.windows.registry.IStringValue	\
	jsaf.intf.windows.registry.IValue	\
	jsaf.intf.windows.system.IWindowsSession	\
	jsaf.intf.windows.wmi.ISWbemEventSource	\
	jsaf.intf.windows.wmi.ISWbemObject	\
	jsaf.intf.windows.wmi.ISWbemObjectSet	\
	jsaf.intf.windows.wmi.ISWbemProperty	\
	jsaf.intf.windows.wmi.ISWbemPropertySet	\
	jsaf.intf.windows.wmi.IWmiProvider	\
	jsaf.provider.Configurator	\
	jsaf.provider.SessionException	\
	jsaf.provider.SessionFactory	\
	jsaf.provider.windows.Timestamp	\
	jsaf.provider.windows.powershell.PowershellException	\
	jsaf.provider.windows.registry.RegistryException	\
	jsaf.provider.windows.wmi.WmiException	\
	jsaf.util.Base64	\
	jsaf.util.Checksum	\
	jsaf.util.IniFile	\
	jsaf.util.PropertyUtil	\
	jsaf.util.SafeCLI	\
	jsaf.util.StringTools
