CLASSES=\
	jsaf.JSAFSystem	\
	jsaf.Message	\
	jsaf.identity.IdentityException	\
	jsaf.intf.apple.system.IiOSSession	\
	jsaf.intf.cisco.system.IAsaSession	\
	jsaf.intf.cisco.system.ICiscoSession	\
	jsaf.intf.cisco.system.IIosSession	\
	jsaf.intf.cisco.system.IIosXeSession	\
	jsaf.intf.cisco.system.ITechSupport	\
	jsaf.intf.discovery.IDiscoveryService	\
	jsaf.intf.identity.ICredential	\
	jsaf.intf.identity.ICredentialStore	\
	jsaf.intf.io.IFile	\
	jsaf.intf.io.IFileEx	\
	jsaf.intf.io.IFileMetadata	\
	jsaf.intf.io.IFilesystem	\
	jsaf.intf.io.IRandomAccess	\
	jsaf.intf.io.IReader	\
	jsaf.intf.juniper.system.IJunosSession	\
	jsaf.intf.juniper.system.ISupportInformation	\
	jsaf.intf.netconf.INetconf	\
	jsaf.intf.remote.IConnectionSpecification	\
	jsaf.intf.remote.IConnectionSpecificationFactory	\
	jsaf.intf.service.IDatabase	\
	jsaf.intf.service.ILightweightDirectory	\
	jsaf.intf.ssh.identity.ISshCredential	\
	jsaf.intf.ssh.system.IShell	\
	jsaf.intf.ssh.system.ISshProcess	\
	jsaf.intf.system.IComputerSystem	\
	jsaf.intf.system.IEnvironment	\
	jsaf.intf.system.IProcess	\
	jsaf.intf.system.ISession	\
	jsaf.intf.unix.identity.IDirectory	\
	jsaf.intf.unix.identity.IGroup	\
	jsaf.intf.unix.identity.IUser	\
	jsaf.intf.unix.io.IUnixFileInfo	\
	jsaf.intf.unix.io.IUnixFilesystem	\
	jsaf.intf.unix.system.IUnixSession	\
	jsaf.intf.util.IConfigurable	\
	jsaf.intf.util.IDisposable	\
	jsaf.intf.util.ILoggable	\
	jsaf.intf.util.IPerishable	\
	jsaf.intf.util.IProperty	\
	jsaf.intf.util.ISearchable	\
	jsaf.intf.windows.identity.IACE	\
	jsaf.intf.windows.identity.IDirectory	\
	jsaf.intf.windows.identity.IGroup	\
	jsaf.intf.windows.identity.IPrincipal	\
	jsaf.intf.windows.identity.IUser	\
	jsaf.intf.windows.identity.IWindowsCredential	\
	jsaf.intf.windows.io.IWindowsFileInfo	\
	jsaf.intf.windows.io.IWindowsFilesystem	\
	jsaf.intf.windows.powershell.IRunspace	\
	jsaf.intf.windows.powershell.IRunspacePool	\
	jsaf.intf.windows.registry.IBinaryValue	\
	jsaf.intf.windows.registry.IDwordBigEndianValue	\
	jsaf.intf.windows.registry.IDwordValue	\
	jsaf.intf.windows.registry.IExpandStringValue	\
	jsaf.intf.windows.registry.IFullResourceDescriptorValue	\
	jsaf.intf.windows.registry.IKey	\
	jsaf.intf.windows.registry.ILinkValue	\
	jsaf.intf.windows.registry.IMultiStringValue	\
	jsaf.intf.windows.registry.INoneValue	\
	jsaf.intf.windows.registry.IQwordValue	\
	jsaf.intf.windows.registry.IRegistry	\
	jsaf.intf.windows.registry.IResourceListValue	\
	jsaf.intf.windows.registry.IResourceRequirementsListValue	\
	jsaf.intf.windows.registry.IStringValue	\
	jsaf.intf.windows.registry.IValue	\
	jsaf.intf.windows.system.IWindowsSession	\
	jsaf.intf.windows.wmi.ISWbemEventSource	\
	jsaf.intf.windows.wmi.ISWbemObject	\
	jsaf.intf.windows.wmi.ISWbemObjectSet	\
	jsaf.intf.windows.wmi.ISWbemProperty	\
	jsaf.intf.windows.wmi.ISWbemPropertySet	\
	jsaf.intf.windows.wmi.IWmiProvider	\
	jsaf.io.LittleEndian	\
	jsaf.io.PerishableReader	\
	jsaf.io.SimpleReader	\
	jsaf.io.StreamLogger	\
	jsaf.io.Streams	\
	jsaf.io.TruncatedInputStream	\
	jsaf.protocol.tftp.TftpURLConnection	\
	jsaf.protocol.tftp.TftpURLStreamHandler	\
	jsaf.protocol.zip.ZipURLConnection	\
	jsaf.protocol.zip.ZipURLStreamHandler	\
	jsaf.provider.SessionException	\
	jsaf.provider.SessionFactory	\
	jsaf.provider.windows.Timestamp	\
	jsaf.provider.windows.powershell.PowershellException	\
	jsaf.provider.windows.registry.RegistryException	\
	jsaf.provider.windows.wmi.WmiException	\
	jsaf.service.UnsupportedServiceException	\
	jsaf.util.AbstractEnvironment	\
	jsaf.util.Base64	\
	jsaf.util.Bytes	\
	jsaf.util.BoundaryIterator	\
	jsaf.util.BoundaryReaderHandler	\
	jsaf.util.Checksum	\
	jsaf.util.ConnectionSpecification	\
	jsaf.util.Environment	\
	jsaf.util.IniFile	\
	jsaf.util.LogCensor	\
	jsaf.util.LogMessageConveyor	\
	jsaf.util.PropertyUtil	\
	jsaf.util.SafeCLI	\
	jsaf.util.Strings
